[package]
name = "todo_schema_grpc"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.10.0"
tonic-reflection = "0.10.0"
prost = "0.12"

[build-dependencies]
tonic-build = { version = "0.10.0", features = ["prost"] }
