[package]
name = "todo_api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todo_config = { path = "../config" }
todo_core = { path = "../core" }
todo_common = { path = "../common" }
todo_schema_grpc = { path = "../schema_grpc" }
todo_repository = { path = "../repository" }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.0.0-rc.4", features = ["full"] }
hyper-util = { git = "https://github.com/hyperium/hyper-util.git" }
http-body-util = "0.1.0-rc.3"
ioc_container_rs = { version = "0.0.1" }
kti_cqrs_provider_rs = { version = "0.0.1" }
kti_cqrs_rs = { version = "0.0.1" }
chrono = "0.4.31"
