[package]
name = "todo_core"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todo_common = { path = "../common" }
todo_repository = { path = "../repository" }
sqlx = { version = "0.7.1", features = [
  "runtime-tokio",
  "postgres",
  "uuid",
  "time",
  "chrono",
] }
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
async-trait = "0.1.73"
ioc_container_rs = { version = "0.0.1" }
kti_cqrs_rs = { version = "0.0.1" }
