[package]
name = "todo_repository"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todo_common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7.1", features = [
  "runtime-tokio",
  "postgres",
  "uuid",
  "time",
  "chrono",
  "macros",
] }
async-trait = "0.1.73"
